OAuth2Project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('users.urls')),
    path('api-auth/', include('rest_framework.urls')),
    # path('api/',include(('users.api.urls','user-api'),namespace='user-api')),
    path('api/',include('users.api.urls')),
    path('o/', include('oauth2_provider.urls', namespace='oauth2_provider')),
]

if settings.DEBUG:
    # import debug_toolbar
    # urlpatterns += [path('__debug__/', include(debug_toolbar.urls))]
    # uncomment if you removed above temporary
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)

users/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import (SignUpView, UserLoginView, UserLogoutView, CustomPasswordResetView,UserProfileView, 
DeleteProfileImage, Home)
app_name = 'users'
urlpatterns = [
    path('', Home.as_view(), name='home'),
    path('signup/', SignUpView.as_view(), name='signup'),
    path('login/', UserLoginView.as_view(), name='login'),
    path('profile/', UserProfileView.as_view(), name='user-profile'),
    path('delete-image/', DeleteProfileImage.as_view(), name='delete-image'),
    path('logout/', UserLogoutView.as_view(), name='logout'),
    path('password_reset/', CustomPasswordResetView.as_view(), name='password_reset'),
    path('', include('django.contrib.auth.urls')),
    
]

templates/base/all_notification.html
{% load static %}
{% load humanize %}
{% load tz %}
<ul class="list-unstyled">
    
</ul>

templates/base/css.html
{% load static %}

<!-- Start css -->

<!-- jQuery UI css -->
<link href="{% static 'assets/plugins/jquery-ui/jquery-ui.min.css' %}" rel="stylesheet" type="text/css" />
<!-- jQuery Confirm css -->
<link href="{% static 'assets/plugins/jquery-confirm/css/jquery-confirm.css' %}" rel="stylesheet" type="text/css">

<link href="{% static 'assets/css/bootstrap.min.css' %}" rel="stylesheet" type="text/css" />

<!-- main style css -->
<link href="{% static 'assets/css/style.css' %}" rel="stylesheet" type="text/css" />

<!-- Mystyle css -->
<link href="{% static 'css/mystyle.css' %}" rel="stylesheet" type="text/css" />

<!--color change-->
<link rel="stylesheet" href="{% static 'colorscheme/css/default.css' %}" type="text/css" />
<link id="theme-style" rel="stylesheet" type="text/css" href="" />
<!-- End css -->

templates/base/js.html
{% load static %}
<!-- End Containerbar -->
<!-- Start js -->
<script defer src="{% static 'assets/js/jquery.min.js' %}"></script>
<script defer src="{% static 'assets/plugins/jquery-ui/jquery-ui.min.js' %}"></script>
<script defer src="{% static 'assets/js/popper.min.js' %}"></script>
<script defer src="{% static 'assets/js/jquery.slimscroll.js' %}"></script>
<script defer src="{% static 'assets/js/bootstrap.min.js' %}"></script>
<!-- jQuery Confirm js -->
<script defer src="{% static 'assets/plugins/jquery-confirm/js/jquery-confirm.js' %}"></script>
<script defer src="{% static 'js/profile.js' %}"></script>
<!-- Core js -->
<script defer src="{% static 'assets/js/core.js' %}"></script>
<!--custom js-->
<script defer src="{% static 'js/csrf.ajax.js' %}"></script>
<!--color change-->
<script defer type="text/javascript" src="{% static 'colorscheme/js/script.js' %}"></script>


<!-- End js -->

templates/base/messages.html
{% block content %}
{% if messages %}

            
                {% for message in messages %}
                    {% comment %}<div class="alert alert-primary" role="alert" style="list-style-type: none"><li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li></div>{% endcomment %}
                    <div class="alert alert-{{ message.tags }}" role="alert" id="message-div-alert">{{ message }}</div>
                {% endfor %}
            
<h1>{{extra_context}}</h1>
{% elif extra_context %}
    <div class="container text-center" id="message-div">
        <div class="row">
                <div class="col-md-12">
                    <div class="alert alert-secondary" role="alert" id="message-div-alert">
                    {{logout_message}}
                    </div>
                </div>
        </div>
</div>
{% endif %}


{% endblock content %}

templates/base/navbar.html
{% load static %} {% block content %} 

    <!-- Start Infobar Setting Sidebar -->
    <div id="infobar-settings-sidebar" class="infobar-settings-sidebar">
        <div class="infobar-settings-sidebar-head d-flex w-100 justify-content-between">
            <h4>Settings</h4><a href="javascript:void(0)" id="infobar-settings-close" class="infobar-settings-close"><i class="ri-close-line menu-hamburger-close"></i></a>
        </div>
        <div class="infobar-settings-sidebar-body">
            <div class="custom-mode-setting">
                <div class="row align-items-center pb-3">
                    <div class="col-8"><h6 class="mb-0">Payment Reminders</h6></div>
                    <div class="col-4"><input type="checkbox" class="js-switch-setting-first" checked /></div>
                </div>
                <div class="row align-items-center pb-3">
                    <div class="col-8"><h6 class="mb-0">Stock Updates</h6></div>
                    <div class="col-4"><input type="checkbox" class="js-switch-setting-second" checked /></div>
                </div>
                <div class="row align-items-center pb-3">
                    <div class="col-8"><h6 class="mb-0">Open for New Products</h6></div>
                    <div class="col-4"><input type="checkbox" class="js-switch-setting-third" /></div>
                </div>
                <div class="row align-items-center pb-3">
                    <div class="col-8"><h6 class="mb-0">Enable SMS</h6></div>
                    <div class="col-4"><input type="checkbox" class="js-switch-setting-fourth" checked /></div>
                </div>
                <div class="row align-items-center pb-3">
                    <div class="col-8"><h6 class="mb-0">Newsletter Subscription</h6></div>
                    <div class="col-4"><input type="checkbox" class="js-switch-setting-fifth" checked /></div>
                </div>
                <div class="row align-items-center pb-3">
                    <div class="col-8"><h6 class="mb-0">Show Map</h6></div>
                    <div class="col-4"><input type="checkbox" class="js-switch-setting-sixth" /></div>
                </div>
                <div class="row align-items-center pb-3">
                    <div class="col-8"><h6 class="mb-0">e-Statement</h6></div>
                    <div class="col-4"><input type="checkbox" class="js-switch-setting-seventh" checked /></div>
                </div>
                <div class="row align-items-center">
                    <div class="col-8"><h6 class="mb-0">Monthly Report</h6></div>
                    <div class="col-4"><input type="checkbox" class="js-switch-setting-eightth" checked /></div>
                </div>
            </div>
        </div>
    </div>
    <div class="infobar-settings-sidebar-overlay"></div>
    <!-- End Infobar Setting Sidebar -->
 {% endblock content %}

templates/base/notification.html
{% load static %}
{% load humanize %}
{% load tz %}
<div class="dropdown">
    <a class="dropdown-toggle infobar-icon" href="#" role="button"
        id="notoficationlink" data-toggle="dropdown" aria-haspopup="true"
        aria-expanded="false"><i class="ri-notification-line dark-icon-color"></i>

        {% if notify_total_count %}<span class="live-icon notify "
            {% if notify_total_count > 9 %}
            style="font-size:xx-small;padding:0 0 0 2px" {% endif %}>
            {{notify_total_count}} </span>{% endif %}</a>

    {% if notify_total_count %}
    <div class="dropdown-menu dropdown-menu-right"
        aria-labelledby="notoficationlink">
        <div class="notification-dropdown-title">
            <h5>Notification<a href="#">Close</a></h5>
        </div>

        {% include 'base/all_notification.html' %}

    </div>
    {% else %}
    <div class="dropdown-menu dropdown-menu-right"
        aria-labelledby="notoficationlink">
        <div class="notification-dropdown-title">
            <h5>No New Notification</h5>
        </div>
        <div class="notification-dropdown-footer pt-0">
            <h5><a href="#">Close</a></h5>
        </div>
    </div>
    {% endif %}


</div>

templates/base/rightbar.html
{% load static %} {% load humanize %} 

{% include 'base/topbar.html' %} 

templates/base/topbar.html
{% load static %} {% load humanize %}


<!-- Start Topbar -->
<div class="topbar w-100 dark-top-color-theme">
  <!-- Start row -->
  <div class="row align-items-center">
    <!-- Start col -->
    <div class="col-md-12 align-self-center">
            <div class="menubar d-inline">
              <a class="menu-hamburger" href="{% url 'users:home' %}">
                Home
              </a>
            </div>

      <div class="infobar">
        <ul class="list-inline mb-0">
          
          <li class="list-inline-item">
            <div class="settingbar">
              <a
                href="javascript:void(0)"
                id="infobar-settings-open"
                class="infobar-icon"
                ><i class="ri-settings-line dark-icon-color"></i
              ></a>
            </div>
          </li>

          <li class="list-inline-item">
            <div class="notifybar">{% include 'base/notification.html' %}</div>
          </li>

          {
          <li class="list-inline-item">
            <div class="profilebar">
              <div class="dropdown">
                <a
                  class="dropdown-toggle"
                  href=""
                  role="button"
                  id="profilelink"
                  data-toggle="dropdown"
                  aria-haspopup="true"
                  aria-expanded="false"
                >
                  <img
                    src="{% if user.userprofile.image %}{{user.userprofile.image.url}}{% endif %}"
                    class="profile-pic-icon"
                    alt=""
                  />
                  <span class="live-icon dark-icon-color dark-theme-border"
                    >{% if user.is_authenticated %}
                    {{user.name|default_if_none:user.username}} {% endif %}
                  </span>
                </a>
                <div
                  class="dropdown-menu dropdown-menu-right"
                  aria-labelledby="profilelink"
                >
                  <a class="dropdown-item" href="{% url 'users:user-profile' %}"
                    ><i class="ri-user-6-line"></i>My Profile</a
                  >
                  {% if user.is_superuser or user.is_staff %}<a
                    class="dropdown-item"
                    target="_blank"
                    href="/admin/"
                    ><i class="ri-admin-line"></i>Admin</a
                  >{% endif %}
                  <a class="dropdown-item setting-class" href=""
                    ><i class="ri-settings-3-line"></i>Settings</a
                  >
                  <a class="dropdown-item" href="{% url 'users:logout' %}"
                    ><i class="ri-shut-down-line"></i>Logout</a
                  >
                </div>
              </div>
            </div>
          </li>
        </ul>
      </div>
    </div>
    <!-- End col -->
  </div>
  <!-- End row -->
</div>
<!-- End Topbar -->